### ISSUE TITLE
Need of toro.py in the source code

### ISSUE THREAD

**Issue by Putti** [goavki/apertium-apy#23]
Could we just delete toro.py from apertium apy source code and add to the wiki instructions to install it with pip or via operating system's package manager? Or is it possible to move completely to tornado's locks so that we wouldn't even need toro?

**Comment by unhammer** [comment]
toro.py is there for people who can't use the new tornado.
```
try:  # >=4.2
    import tornado.locks as locks
except ImportError:
    import toro as locks
```

**Comment by Putti** [comment]
What about installing it via pip / distro's package manager? The user will have it then in one place as a shared module and so she/he wouldn't need to fill so much space (as it would take so much space...) in the mass storage device! :D

**Comment by unhammer** [comment]
We originally assumed users would pip install toro.py, but that was a problem for using APY on wikimedia's servers, because they want only stuff they can install as .deb's, understandably. So since toro.py is *tiny* and self-contained, we just put it in APY.

If toro existed in distro package managers, all would be peacy, but toro *became* tornado 4.2's locks, so no one's going to package it because it's simply not worth the effort. The reason we keep it around is to support running APY with the minimum of fuss on very old systems. When those old systems don't exist any more (ie. are no longer getting security updates), we'll throw out toro.py (and the if-statement in translation.py). Until then, we don't have to think about it.
