### ISSUE TITLE
/list?q=pairs return data differs from rest of the modes

### ISSUE THREAD

**Issue by ghost** [goavki/apertium-apy#26]
/list?q=pairs return data differs from rest of the modes. It produces:

```
$ curl 'http://localhost:2737/list?q=pairs'

{"responseStatus": 200, "responseData": [
 {"sourceLanguage": "kaz", "targetLanguage": "tat"}, 
 {"sourceLanguage": "tat", "targetLanguage": "kaz"}, 
 {"sourceLanguage": "mk", "targetLanguage": "en"}
], "responseDetails": null}

```

and the rest are like:

```
$ curl 'http://localhost:2737/list?q=analyzers'
{"mk-en": "mk-en-morph", "en-es": "en-es-anmor", "kaz-tat": "kaz-tat-morph", 
 "tat-kaz": "tat-kaz-morph", "fin": "fin-morph", "es-en": "es-en-anmor", "kaz": "kaz-morph"}
```

Should we just remove the pairs mode from /list and have only /listPairs?

**Comment by sushain97** [comment]
No. This is to maintain compatibility with ScaleMT.

**Comment by Putti** [comment]
Okay. Hmm, we have this problem in issue #12 that the specification tool doesn't allow us to return different data types. What do we do with it? Should we just remove it from spec and have it as deprecated?

**Comment by Putti** [comment]
Couldn't we also change the ScaleMT to work with these changes?

**Comment by unhammer** [comment]
(reposting from IRC to keep everything in one place):

> <Unhammer> maintaining scalemt compatability is for *clients* that expect scalemt api, so changing the  ScaleMT server wouldn't help :-)  I think I would rather just leave such unspeccable endpoints out of the spec for now.

>  <Putti> Unhammer, okay so /listPairs for pair info and /list?q=analyser/generator/etc for the others (not ?q=pairs) 

Agreed, let's just keep `q=pairs  out of the spec for now.

**Comment by unhammer** [comment]
I just had a look at http://wiki.apertium.org/wiki/Apertium_scalable_service#API_Specification and it seems it's `listPairs` that's from ScaleMT, while `list?q=pairs` is something that's pure Apy. 

I'm actually in favour of having the ScaleMT-like structure everywhere, ie. `/list?q=analyzers` should also return
`{"responseStatus": 200, "responseData": …, "responseDetails": null}`.

Unfortunately, the responseData value would still have to differ from the one in `/list?q=pairs` (and it doesn't make much sense to try to fit one into the structure of the other), so that doesn't help much with the spec :-/
