### ISSUE TITLE
Chained translations

### ISSUE THREAD

**Issue by ghost** [goavki/apertium-apy#28]
As discussed in apertium's IRC channel it would be nice to have chained translations, for example Sardinian -> Italian -> Spanish. So some code needs to be done that creates a path which the source text needs to go trough in order to achieve the wanted translation. Also some flag etc. that enables these chained translations.

**Comment by shardulc** [comment]
I would like to work on this for my [GCI task](https://codein.withgoogle.com/dashboard/task-instances/6239254105554944/). Do I have to find the shortest path between two languages, or should the user specify the path, or both? If I have to find the path, can it be a simple search or should it take into account coverage, accuracy (where can I get this data?), or anything else? Thanks!

**Comment by Putti** [comment]
Shortest path sounds good as for now there is no easy way to find out which pairs have the best translation quality. Btw, the flag when enabled should then show the possible pairs in /listPairs (maybe differentely than the others if needed).

**Comment by Putti** [comment]
And for the shortest path algortihm try to find some pre-existing function from standard python library (or some other one we're using) that has that already that implemented.

**Comment by sushain97** [comment]
Also, cache the path. The response JSON should indicate that a chained translation occurred and report the path that was taken. Also, it would be nice to have support for langpair being chained, .e.g. "en-es-fr".

**Comment by Putti** [comment]
I think also that one level of chaining is enough. @shardulc I checked the standard library and it didn't have anything related to graph theory, so you need to implement the shortest path finding yourself. I suggest dijkstra's algorithm. For the graph maybe something like 
```
{"fra": ["spa","cat"], "spa": ["fra"], "cat": ["fra"]}
```

**Comment by shardulc** [comment]
@Putti OK, I will implement it. I was thinking about doing a simple breadth-first search (since the edges in the graph are unweighted) but I will see if Dijkstra's is faster.

@sushain97 Caching can simply be in a dict, right? I assume new language pairs are added very infrequently so that the cached paths do not become 'old'. When you say "support for langpair being chained", do you mean the GET request itself could be of the form "...&langPair=en-es-fr&..."? If this is not specified, a shortest path would be calculated or loaded from the cache.

**Comment by Putti** [comment]
@shardulc BFS is fine, too.

**Comment by sushain97** [comment]
This is supported now. Any enhancements/bugs belong in new issues.
